config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Favorites routes
  resources :resources do
    resources :favorites, only: [:create, :destroy]
  end
  resources :favorites, only: [:index]

  root to: "resources#index"

  #Sessions routes
  resources :sessions, only: [:create, :new]
  delete 'sessions', to: 'sessions#logout'

  #Users routes
  resources :users
  get '/users/:user_id/my_resources', to: 'users#teachers_my_show', as: 'my_resources'
  get '/users/:user_id/my_favorites', to: 'users#teachers_my_fav', as: 'my_favorites'
  #Resources routes
  resources :resources
  post '/resources/search', to: 'resources#search', as: 'search_resources'


  #Tags routes
  resources :resources do
    resources :resource_tags, only: [:new, :create]
  end

  #Resource_tags routes
  resources :resource_tags, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :fan, class_name: "User"
  belongs_to :resource

  validates :fan_id, :resource_id, presence: true
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_many :resource_tags
  has_many :tags, through: :resource_tags
  has_many :favorites
  has_many :fans, through: :favorites
  belongs_to :author, class_name: "User"

  validates :title, :url, :author, presence: true

  # Resource.joins(ResourceTag.joins(:tag).where("tags.permission = false").group(:resource_id).count).where((:resource_id).count = 0)

  def self.resources_by_tags(tag)
    tagged = Resource.joins(:tags).where( tags: { name: tag } )
  end

  # Can be refactored
  # def self.resources_by_tag(tag)
  #   tag_obj = Tag.find_by(name: tag)
  #   filtered = Resource.all.reduce(Array.new) do |arr, resource|
  #     if resource.tags.include?(tag_obj)
  #       arr << resource
  #     end
  #   end
  #   filtered
  # end

  #Can be refactored
  def teachers_only?
    !!self.tags.find_by(permission: false)
  end

  def favorites_count
    self.fans.count
  end

end

app/models/resource_tag.rb
class ResourceTag < ApplicationRecord
  belongs_to :tag
  belongs_to :resource

  validates_uniqueness_of :tag_id, :scope => [:resource_id]

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :resource_tags
  has_many :resources, through: :resource_tags

  validates :name, presence: :true
  validates :name, uniqueness: :true


end

app/models/user.rb
class User < ApplicationRecord
  has_many :resources_posted, class_name: "Resource", foreign_key: :author_id
  has_many :favorites, foreign_key: :fan_id
  has_many :resources_favorited, through: :favorites, source: :resource

  validates :first_name, :last_name, :email, :user_type, presence: true
  validates :email, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  include SessionsHelper

  def index
    @favorited_resources = current_user.resources_favorited

    respond_to do |f|
      f.html { render :_index}
      f.json { render json: @favorited_resources.to_json}
      f.js
    end
  end

  def show

  end

  def new

  end

  def create
    @favorite = current_user.favorites.find_or_create_by(resource_id: params[:resource_id])
    redirect_to :back
  end

  def edit

  end

  def update

  end

  def destroy
    @favorite = current_user.favorites.find(params[:id])

    @favorite.destroy
    redirect_to favorites_path
  end

end

app/controllers/resource_tags_controller.rb
class ResourceTagsController < ApplicationController
  include SessionsHelper

  def new
    @tag = Tag.new
    render :new
  end

  def create
    find_tag
    @resource_tag = ResourceTag.new(resource: find_resource, tag: find_tag)
    if @resource_tag.tag_id == nil
      @errors = ["This tag is already associated with the resource"]
      @tag = Tag.new(name: find_tag.name)
      render :new
    elsif @resource_tag.save
      redirect_to user_path(current_user)
    else
      @errors = ["This tag is already associated with the resource"]
      @tag = Tag.new(name: find_tag.name)
      render :new
    end
  end

  def destroy
    @resource_tag = ResourceTag.find(params[:id])
    @resource_tag.destroy
    redirect_to user_path(current_user)

    #@resource_tag = ResourceTag.where(resource: params[:resource_id], tag: tag.id)
    #resource_tag_id = @resource_tag.id
    #ResourceTag.destroy(resource_tag_id)
  end

  private

  def tag_attributes
    params.require(:tag).permit(:name, :permission)
  end

  def find_tag
    @tag = Tag.find_or_create_by(tag_attributes)
  end

  def find_resource
    @resource = Resource.find(params[:resource_id])
  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  include SessionsHelper

  def index
    @resources = Resource.all
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.new(resource_params)
    @resource.author = current_user

    if @resource.save
      redirect_to user_path(current_user)
    else
      @error = @resource.errors.full_messages
      render :new
    end
  end

  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy
    redirect_to user_path(current_user)
  end

  def search
    tag = search_params[:tag]
    @resources = Resource.resources_by_tags(tag)

    if !logged_in?
      render :index
    elsif current_user.user_type == "teacher"
      render :'users/teacher_show'
    else
      render :'users/student_show'
    end
  end

  private

  def resource_params
    params.require(:resource).permit(:title, :url)
  end

  def search_params
    params.permit(:tag)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def create
    @user = User.find_by_email(session_params[:email])
       if @user && @user.authenticate(session_params[:password])
         login(@user)
         redirect_to user_path(@user)
       else
         @errors = ["Wrong email or password"]
         render :new
       end
  end

  def new
  end

  def logout
    session[:id]= nil
    redirect_to root_path
  end

  def session_params
    params.permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include SessionsHelper

  def show
      if current_user && current_user.user_type == 'teacher'
        @resources = Resource.all
        @favorited_resources = current_user.resources_favorited
        render :teacher_show
      elsif current_user && current_user.user_type == 'student'
        @resources = Resource.all
        @favorited_resources = current_user.resources_favorited
        render :student_show
      else
        @errors = ["Please sign in"]
        render :'resources/index'
      end
  end

  def teachers_my_show
    @resources = current_user.resources_posted
    respond_to do |format|
      format.html { render :teacher_show }
      format.json { render partial: '/partials/teachers_resource_display' }
    end

  end

  def teachers_my_fav
    @resources = current_user.resources_favorited
    render :teacher_show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.user_type = params[:user_type]
    if @user.save
      session[:id] = @user.id
      redirect_to user_path(@user), notice: "User was successfully created."
    else
      @errors = @user.errors.full_messages
      render :new, status: 422
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to sessions_path, notice: "User was successfully destroyed."
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :user_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def find_favorite(user, resource)
    Favorite.find_by(fan_id: user.id, resource_id: resource.id)
  end


  ##can use zip and associations to create a hash that I can iterate through for finding favorites
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:id] = @user.id
  end

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end

  def logged_in?
    !!current_user
  end

 end

app/views/favorites/_index.html.haml
%H2 Your Favorite Resources

%ul
  -@favorited_resources.each do |resource|
    %br
    %li.resource-item
      %ul.resource-details
        %li.resource-title= resource.title
        %li.resource-url= link_to resource.url, resource.url
        %li.resource-tages
          -resource.tags.each do |tag|
            %span.badge-info= tag.name
        %li.resource-fans
          Fans:
          = resource.favorites_count
        %div.btn.btn-outline-secondary
          = bootstrap_form_for(:favorite, url: resource_favorite_path(resource_id: resource.id, id: find_favorite(current_user, resource).id), method: "DELETE") do |f|
            = f.submit("Remove Favorite")

app/views/favorites/index.html.haml
%H2 Your Favorite Resources

%ul
  -@resources.each do |resource|
    %br
    %li.resource-item
      %ul.resource-details
        %li.resource-title= resource.title
        %li.resource-url= link_to resource.url, resource.url
        %li.resource-tages
          -resource.tags.each do |tag|
            %span.badge-info= tag.name
        %li.resource-fans
          Fans:
          = resource.favorites_count
        %div.btn.btn-outline-secondary
          = bootstrap_form_for(:favorite, url: resource_favorite_path(resource_id: resource.id, id: find_favorite(current_user, resource).id), method: "DELETE") do |f|
            = f.submit("Remove Favorite")

app/views/favorites/index.js.erb
$('.favorites-partial').html("<%= j (render 'favorites/index') %>").toggle()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sorcerer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-brand">Sourcerer</div>
        <div class="nav-link">
          <%= link_to "Home", resources_path  %>
        </div>
        <% if logged_in?  %>
          <div class="nav-link">
          <%= link_to "My Profile", user_path(current_user)  %>
          </div>
          <div class="form-inline my-2 my-lg-0">
            <%= form_tag(controller: 'resources', action: 'search', :method => 'get') do %>
              <input class="form-control mr-sm-2" name="tag" placeholder="Search" type="text"></input>
              <input class="btn btn-outline-info my-2 my-sm-0" type="submit"></input>
            <% end %>
          </div>
          <div class="nav-link">
          <%= link_to "Logout", sessions_path, method: "DELETE" %>
          </div>
        <% else %>
        <div class="nav-link">
          <%= link_to "Login", new_session_path %>
        </div>
        <div class="nav-link">
          <%= link_to "Register", new_user_path  %>
        </div>
        <% end %>
      </nav>
    </header>


    <%= yield %>

    <% if @errors %>
      <ul class="alert alert-danger">
      <% @errors.each do |error| %>
        <li><%= error %></li>
      </ul>
      <% end %>
    <% end %>
  </body>
</html>

app/views/partials/_teachers_resource_display.html.haml
-@resources.each do |resource|
  %li.resource-item
    %ul.resource-details
      %li.resource-title
        = resource.title
        %span.resource-delete= link_to "x", resource_path(resource), method: "DELETE", data: { confirm: "Are you sure?"}
      %li.resource-url= link_to resource.url, resource.url
      - if resource.tags.count != 0
        %li.resource-tags
          - resource.tags.each do |tag|
            %span.badge.badge-info= tag.name
            %span= link_to "x", resource_tag_path((ResourceTag.find_by_resource_id_and_tag_id(resource.id, tag.id))), method: "DELETE",data: { confirm: "Are you sure?"}
      %li= link_to "+ tag", new_resource_resource_tag_path(resource)
      %li.resource-fans
        Fans:
        = resource.favorites_count
      - if !current_user.resources_favorited.include?(resource)
        %li.favorite-button
          = form_for(:favorite, url: resource_favorites_path(resource.id), method:"POST") do |f|
            = f.submit

app/views/resource_tags/new.html.haml
%h2 Add a Tag

%div.container
=bootstrap_form_for @tag, url: resource_resource_tags_path do |f|
  =f.text_field :name
  =f.check_box :permission

  %p.btn.btn-outline-info.my-2.my-sm-0
  =f.submit

app/views/resources/_teachers_resource_display.html.haml
-@resources.each do |resource|
  %li.resource-item
    %ul.resource-details
      %li.resource-title
        = resource.title
        %span.resource-delete= link_to "x", resource_path(resource), method: "DELETE"
      %li.resource-url= link_to resource.url, resource.url
      - if resource.tags.count != 0
        %li.resource-tags
          - resource.tags.each do |tag|
            %span= tag.name
            %span= link_to "x", resource_tag_path((ResourceTag.find_by_resource_id_and_tag_id(resource.id, tag.id))), method: "DELETE"
        %li= link_to "+ tag", new_resource_resource_tag_path(resource)
      %li.resource-fans
        Fans:
        = resource.favorites_count
      - if !current_user.resources_favorited.include?(resource)
        %li.favorite-button
          = form_for(:favorite, url: resource_favorites_path(resource.id), method:"POST") do |f|
            = f.submit

app/views/resources/index.html.haml
%h1 Resources

-# %div.search-bar
-#   = form_tag(controller: 'resources', action: 'search', :method => 'get') do
-#     %input{type: 'text', name: 'tag', placeholder: 'Search'}
-#     %input{type: 'submit'}

%br
%ul
  -@resources.each do |resource|
    %br
    -if resource.teachers_only?
    -else
      %li.resource-item
        %ul.resource-details
          %li.resource-title= resource.title
          %li.resource-url= link_to resource.url, resource.url
          %li.resource-tags
            - resource.tags.each do |tag|
              %span= tag.name
          %li.resource-fans
            Fans:
            = resource.favorites_count

app/views/resources/new.html.haml
%H2 Add a Resource
%div.container
  =bootstrap_form_for @resource, url: {action: "create"} do |f|
    =f.text_field :title
    =f.text_field :url

    %p.btn.btn-outline-info.my-2.my-sm-0
    =f.submit

app/views/users/_teachers_resource_display.html.haml
-@resources.each do |resource|
  %li.resource-item
    %ul.resource-details
      %li.resource-title
        = resource.title
        %span.resource-delete= link_to "x", resource_path(resource), method: "DELETE"
      %li.resource-url= link_to resource.url, resource.url
      - if resource.tags.count != 0
        %li.badge.badge-info
          - resource.tags.each do |tag|
            %div.badge.badge-info
              %span.badge.badge-info= tag.name
              %span.badge.badge-info= link_to "x", resource_tag_path((ResourceTag.find_by_resource_id_and_tag_id(resource.id, tag.id))), method: "DELETE"
        %li= link_to "+ tag", new_resource_resource_tag_path(resource)
      %li.resource-fans
        Fans:
        = resource.favorites_count
      - if !current_user.resources_favorited.include?(resource)
        %li.favorite-button
          = form_for(:favorite, url: resource_favorites_path(resource.id), method:"POST") do |f|
            = f.submit

app/views/users/new.html.haml
%h2 Registration Form

%div.container
  = bootstrap_form_for @user do |f|
    %p
      -# = f.label :first_name
      = f.text_field :first_name

    %p
      -# = f.label :last_name
      = f.text_field :last_name

    %p
      -# = f.label :email
      = f.email_field :email

    %p
      -# = f.label :password
      = f.password_field :password

    %p
      -# = f.label :user_type
      %select{ :name => "user_type" }
        %option{:value => "student"}= "Student"
        %option{:value => "teacher"}= "Teacher"

    %p.btn.btn-outline-info.my-2.my-sm-0
      = f.submit

app/views/users/student_show.html.haml
%H2
  Hello
  = current_user.first_name.capitalize

%ul.resources-classification
  %li.favorites-link= link_to "My Favorites", favorites_path, remote: true
  %div.favorites-partial

%ul.container
  -@resources.each do |resource|
    -if resource.teachers_only?
    -else
      %br
      %li.resource-item
        %ul.resource-details
          %li.resource-title= resource.title
          %li.resource-url= link_to resource.url, resource.url
          %li.resource-tags
            - resource.tags.each do |tag|
              %span.badge-info= tag.name
          %li.resource-fans
            Fans:
            = resource.favorites_count
          - if !current_user.resources_favorited.include?(resource)
            %li.btn.btn.btn-outline-info
              = bootstrap_form_for(:favorite, url: resource_favorites_path(resource.id), method: "POST") do |f|
                = f.submit

app/views/users/teacher_show.html.haml
-# %div.search-bar
-#   = form_tag(search_resources_path) do
-#     %input{type: 'text', name: 'tag', placeholder: 'Search'}
-#     %input{type: 'submit'}

%br
%ul
  %li.btn.btn-light= link_to "All Resources", user_path(current_user)
  %li.btn.btn-light= link_to "My Favorites", my_favorites_path(current_user)
  %li.btn.btn-light= link_to "My Resources", my_resources_path(current_user)

-# %ul.nav.nav-tabs
-#   %li.btn.btn-light= link_to "All Resources", user_path(current_user)
-#   %li.btn.btn-light= link_to "My Resources", my_resources_path(current_user)
-#   %li.btn.btn-light.favorites-link= link_to "My Favorites", favorites_path, remote: true
-#   %div.favorites-partial

%ul.resources-list
%br
  = render partial: '/partials/teachers_resource_display'

= link_to "Add Resource", new_resource_path

app/views/users/teachers_my_show.js.haml
$('.resources-list').html( "= j (render partial: '/partials/teachers_resource_display')" );